name: preco_mi
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Administrador <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  sass_builder: ^1.0.1
  chartjs: ^0.4.0
  firebase: ^4.1.0
  intl: ^0.15.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- sass_builder
- angular:
      entry_points: web/main.dart
#- angular/transform/reflection_remover:
#    $include: test/**_test.dart
#- test/pub_serve:
#    $include: test/**_test.dart
#- dart_to_js_script_rewriter

#entry_points: web/main.dart

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc